services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-agnos}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    image: agnos-api:latest
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      APP_PORT: "${APP_PORT:-8080}"

      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-agnos}
      DB_SSLMODE: disable

      JWT_SECRET: ${JWT_SECRET:-agnos-assignment-secret-change-me}

      HOSPITAL_A_API_URL: ${HOSPITAL_A_API_URL:-https://hospital-a.api.co.th}

    depends_on:
      postgres:
        condition: service_healthy

    expose:
      - "${APP_PORT:-8080}"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:${APP_PORT:-8080}/health >/dev/null 2>&1 || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s


  nginx:
    image: nginx:alpine

    environment:
      APP_PORT: "${APP_PORT:-8080}"

    ports:
      - "${APP_PORT:-8080}:80"

    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro

    depends_on:
      api:
        condition: service_healthy


volumes:
  postgres_data: